// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXeLvekdvpfvzJBMtHu0R0OHO5c-cwVM',
    appId: '1:937129222872:web:ed86ed430ca9f05edcedad',
    messagingSenderId: '937129222872',
    projectId: 'neuroforge-workflow',
    authDomain: 'neuroforge-workflow.firebaseapp.com',
    storageBucket: 'neuroforge-workflow.firebasestorage.app',
    measurementId: 'G-HJC2CSZ6PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0PqFSx95KqDwjj_73_oEgY_4v1fLuuvE',
    appId: '1:937129222872:android:7a016bb94bb07807dcedad',
    messagingSenderId: '937129222872',
    projectId: 'neuroforge-workflow',
    storageBucket: 'neuroforge-workflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_7UzAvQvEDcntSPgXSwoOVkzqwIpH08',
    appId: '1:937129222872:ios:943d03665ac35689dcedad',
    messagingSenderId: '937129222872',
    projectId: 'neuroforge-workflow',
    storageBucket: 'neuroforge-workflow.firebasestorage.app',
    iosBundleId: 'com.example.neuroforgeWorkflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_7UzAvQvEDcntSPgXSwoOVkzqwIpH08',
    appId: '1:937129222872:ios:943d03665ac35689dcedad',
    messagingSenderId: '937129222872',
    projectId: 'neuroforge-workflow',
    storageBucket: 'neuroforge-workflow.firebasestorage.app',
    iosBundleId: 'com.example.neuroforgeWorkflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMXeLvekdvpfvzJBMtHu0R0OHO5c-cwVM',
    appId: '1:937129222872:web:6623192a938c6343dcedad',
    messagingSenderId: '937129222872',
    projectId: 'neuroforge-workflow',
    authDomain: 'neuroforge-workflow.firebaseapp.com',
    storageBucket: 'neuroforge-workflow.firebasestorage.app',
    measurementId: 'G-CQD2C5V9PN',
  );

}